<a href="https://colab.research.google.com/github/albertohg1/Data_projects_TripleTen/blob/main/supernova_raw_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
file_path='/content/drive/MyDrive/TripleTen/Externship -- Supernova/raw_data.csv'

In [3]:
import pandas as pd
df = pd.read_csv(file_path)
df.head()

,insured_address_state,Industry Code,Category,input_gl_revenue,input_gl_employee,input_gl_gl_limit,input_gl_gl_deductible,input_property_bldg_limit,input_property_num_claims,input_property_town_grade,...,output_premium_bldg_premium,output_premium_flood_premium,output_premium_content_premium,output_premium_on_prem_gl_prem,output_premium_products_gl_prem,output_premium_business_interuption_prem,output_premium_total_total_prem,output_debug_sd_factor_bi,output_debug_sd_factor_gl,output_debug_sd_factor_prop
0,Ontario,5312,Retail,1000000,26,2000000,1000,0,0,3,...,0,0.00,430.56,2668.00,0.0,430.56,4618.39,1.0,1.0,1.0
1,Ontario,5312,Retail,350000,26,2000000,1000,0,0,3,...,0,0.00,1257.24,933.80,0.0,110.01,3666.13,1.0,1.0,1.0
2,Ontario,5811,Hospitality,333333,1,1000000,1000,0,0,3,...,0,3.17,249.33,1866.66,0.0,831.10,3054.95,1.0,1.0,1.0
3,Ontario,5811,Hospitality,300000,1,2000000,1000,0,0,4,...,0,0.00,249.33,1932.00,0.0,747.99,3033.94,1.0,1.0,1.0
4,Ontario,5811,Hospitality,300000,2,2000000,1000,0,0,3,...,0,0.00,223.40,1932.00,0.0,239.36,2575.83,1.0,1.0,1.0

In [4]:
df['insured_address_state'] = df['insured_address_state'].replace('Québec', 'Quebec')

In [5]:
df = df[df['Industry Code'].between(1111, 9281)]

In [6]:
df = df.rename(columns={'Industry Code': 'industry_code'})
df = df[df['industry_code'].between(1111, 9281)]

In [7]:
df.head()

,insured_address_state,industry_code,Category,input_gl_revenue,input_gl_employee,input_gl_gl_limit,input_gl_gl_deductible,input_property_bldg_limit,input_property_num_claims,input_property_town_grade,...,output_premium_bldg_premium,output_premium_flood_premium,output_premium_content_premium,output_premium_on_prem_gl_prem,output_premium_products_gl_prem,output_premium_business_interuption_prem,output_premium_total_total_prem,output_debug_sd_factor_bi,output_debug_sd_factor_gl,output_debug_sd_factor_prop
0,Ontario,5312,Retail,1000000,26,2000000,1000,0,0,3,...,0,0.00,430.56,2668.00,0.0,430.56,4618.39,1.0,1.0,1.0
1,Ontario,5312,Retail,350000,26,2000000,1000,0,0,3,...,0,0.00,1257.24,933.80,0.0,110.01,3666.13,1.0,1.0,1.0
2,Ontario,5811,Hospitality,333333,1,1000000,1000,0,0,3,...,0,3.17,249.33,1866.66,0.0,831.10,3054.95,1.0,1.0,1.0
3,Ontario,5811,Hospitality,300000,1,2000000,1000,0,0,4,...,0,0.00,249.33,1932.00,0.0,747.99,3033.94,1.0,1.0,1.0
4,Ontario,5811,Hospitality,300000,2,2000000,1000,0,0,3,...,0,0.00,223.40,1932.00,0.0,239.36,2575.83,1.0,1.0,1.0

In [8]:
df = df.drop_duplicates()

In [9]:
print("Before:", df.shape)
df = df.drop_duplicates()
print("After:", df.shape)

Before: (174, 27)
After: (174, 27)

In [10]:
# Clean and standardize Category names
category_clean_map = {
    'Health Serv.': 'Health Services',
    'B&P Services': 'Business & Personal Services',
    'Hospitality': 'Hospitality',
    'Retail': 'Retail',
    'Wholesale': 'Wholesale'
}

df['Category'] = df['Category'].str.strip().map(category_clean_map)

In [11]:
df['Category'].value_counts()

Category
Hospitality                     83
Retail                          37
Business & Personal Services    37
Health Services                 15
Wholesale                        2
Name: count, dtype: int64

In [12]:
potential_duplicates = df[df.duplicated(subset=[
    'industry_code', 'insured_address_state', 'Category',
    'input_gl_revenue', 'input_gl_employee', 'input_gl_gl_limit',
    'input_property_bldg_limit', 'input_property_content_limit'
], keep=False)]  # keep=False shows all duplicate pairs

# See how many we found:
print("Potential duplicates found:", potential_duplicates.shape[0])

Potential duplicates found: 49

In [13]:
potential_duplicates.head()

,insured_address_state,industry_code,Category,input_gl_revenue,input_gl_employee,input_gl_gl_limit,input_gl_gl_deductible,input_property_bldg_limit,input_property_num_claims,input_property_town_grade,...,output_premium_bldg_premium,output_premium_flood_premium,output_premium_content_premium,output_premium_on_prem_gl_prem,output_premium_products_gl_prem,output_premium_business_interuption_prem,output_premium_total_total_prem,output_debug_sd_factor_bi,output_debug_sd_factor_gl,output_debug_sd_factor_prop
3,Ontario,5811,Hospitality,300000,1,2000000,1000,0,0,4,...,0,0.00,249.33,1932.0,0.0,747.99,3033.94,1.0,1.0,1.0
5,Ontario,5811,Hospitality,300000,2,2000000,1000,0,0,3,...,0,0.00,79.79,1932.0,0.0,239.36,2420.78,1.0,1.0,1.0
6,Ontario,5811,Hospitality,300000,1,2000000,1000,0,0,3,...,0,0.00,79.79,1932.0,0.0,239.36,2355.78,1.0,1.0,1.0
8,Ontario,5811,Hospitality,200000,2,2000000,1000,0,0,3,...,0,51.26,546.48,1288.0,0.0,109.30,2299.32,1.0,1.0,1.0
16,Ontario,5811,Hospitality,200000,2,2000000,5000,0,0,4,...,0,0.00,79.79,1288.0,0.0,159.57,1696.98,1.0,1.0,1.0

In [14]:
output_path = '/content/drive/My Drive/TripleTen/Externship -- Supernova/cleaned_supernova_data.csv'
df.to_csv(output_path, index=False)

print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!

In [15]:
potential_duplicates.to_csv(
    '/content/drive/My Drive/TripleTen/Externship -- Supernova/potential_policy_duplicates.csv',
    index=False
)
print("📁 Potential duplicates exported for review.")

📁 Potential duplicates exported for review.